// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string achievement_easy_anchor_master = "CgkI87jo_u4MEAIQOw"; // <GPGSID>
        public const string achievement_medium_anchor_apprentice = "CgkI87jo_u4MEAIQPQ"; // <GPGSID>
        public const string achievement_easy_frenzy_expert = "CgkI87jo_u4MEAIQJg"; // <GPGSID>
        public const string achievement_medium_anchor_master = "CgkI87jo_u4MEAIQPw"; // <GPGSID>
        public const string achievement_insane_time_attack_grandmaster = "CgkI87jo_u4MEAIQFA"; // <GPGSID>
        public const string achievement_medium_frenzy_grandmaster = "CgkI87jo_u4MEAIQMA"; // <GPGSID>
        public const string achievement_insane_time_attack_master = "CgkI87jo_u4MEAIQEw"; // <GPGSID>
        public const string achievement_easy_time_attack_expert = "CgkI87jo_u4MEAIQAg"; // <GPGSID>
        public const string achievement_hard_frenzy_apprentice = "CgkI87jo_u4MEAIQMQ"; // <GPGSID>
        public const string achievement_medium_time_attack_master = "CgkI87jo_u4MEAIQBw"; // <GPGSID>
        public const string achievement_play_100_games = "CgkI87jo_u4MEAIQQg"; // <GPGSID>
        public const string achievement_easy_time_attack_grandmaster = "CgkI87jo_u4MEAIQBA"; // <GPGSID>
        public const string achievement_medium_frenzy_apprentice = "CgkI87jo_u4MEAIQLQ"; // <GPGSID>
        public const string achievement_easy_survival_grandmaster = "CgkI87jo_u4MEAIQGA"; // <GPGSID>
        public const string leaderboard_hard_survival = "CgkI87jo_u4MEAIQKQ"; // <GPGSID>
        public const string achievement_easy_time_attack_master = "CgkI87jo_u4MEAIQAw"; // <GPGSID>
        public const string achievement_easy_survival_master = "CgkI87jo_u4MEAIQFw"; // <GPGSID>
        public const string achievement_easy_survival_apprentice = "CgkI87jo_u4MEAIQFQ"; // <GPGSID>
        public const string achievement_hard_survival_expert = "CgkI87jo_u4MEAIQHg"; // <GPGSID>
        public const string achievement_hard_anchor_grandmaster = "CgkI87jo_u4MEAIQRw"; // <GPGSID>
        public const string achievement_insane_anchor_apprentice = "CgkI87jo_u4MEAIQSA"; // <GPGSID>
        public const string achievement_play_10_games = "CgkI87jo_u4MEAIQQQ"; // <GPGSID>
        public const string achievement_insane_survival_master = "CgkI87jo_u4MEAIQIw"; // <GPGSID>
        public const string achievement_easy_time_attack_apprentice = "CgkI87jo_u4MEAIQAQ"; // <GPGSID>
        public const string achievement_insane_anchor_master = "CgkI87jo_u4MEAIQSg"; // <GPGSID>
        public const string achievement_insane_survival_apprentice = "CgkI87jo_u4MEAIQIQ"; // <GPGSID>
        public const string achievement_medium_survival_grandmaster = "CgkI87jo_u4MEAIQHA"; // <GPGSID>
        public const string leaderboard_easy_time_attack = "CgkI87jo_u4MEAIQCQ"; // <GPGSID>
        public const string achievement_insane_anchor_grandmaster = "CgkI87jo_u4MEAIQSw"; // <GPGSID>
        public const string achievement_hard_time_attack_expert = "CgkI87jo_u4MEAIQDg"; // <GPGSID>
        public const string achievement_easy_frenzy_master = "CgkI87jo_u4MEAIQKw"; // <GPGSID>
        public const string achievement_hard_anchor_expert = "CgkI87jo_u4MEAIQRQ"; // <GPGSID>
        public const string achievement_easy_survival_expert = "CgkI87jo_u4MEAIQFg"; // <GPGSID>
        public const string achievement_easy_frenzy_grandmaster = "CgkI87jo_u4MEAIQLA"; // <GPGSID>
        public const string achievement_medium_anchor_expert = "CgkI87jo_u4MEAIQPg"; // <GPGSID>
        public const string leaderboard_medium_survival = "CgkI87jo_u4MEAIQKA"; // <GPGSID>
        public const string achievement_insane_anchor_expert = "CgkI87jo_u4MEAIQSQ"; // <GPGSID>
        public const string achievement_medium_survival_expert = "CgkI87jo_u4MEAIQGg"; // <GPGSID>
        public const string leaderboard_hard_time_attack = "CgkI87jo_u4MEAIQCw"; // <GPGSID>
        public const string leaderboard_easy_frenzy = "CgkI87jo_u4MEAIQTA"; // <GPGSID>
        public const string achievement_medium_time_attack_apprentice = "CgkI87jo_u4MEAIQBQ"; // <GPGSID>
        public const string achievement_insane_frenzy_master = "CgkI87jo_u4MEAIQNw"; // <GPGSID>
        public const string achievement_hard_survival_grandmaster = "CgkI87jo_u4MEAIQIA"; // <GPGSID>
        public const string achievement_easy_frenzy_apprentice = "CgkI87jo_u4MEAIQJQ"; // <GPGSID>
        public const string achievement_play_1000_games = "CgkI87jo_u4MEAIQQw"; // <GPGSID>
        public const string achievement_hard_frenzy_grandmaster = "CgkI87jo_u4MEAIQNA"; // <GPGSID>
        public const string leaderboard_easy_anchor = "CgkI87jo_u4MEAIQUA"; // <GPGSID>
        public const string achievement_hard_anchor_apprentice = "CgkI87jo_u4MEAIQRA"; // <GPGSID>
        public const string leaderboard_easy_survival = "CgkI87jo_u4MEAIQJw"; // <GPGSID>
        public const string achievement_hard_time_attack_grandmaster = "CgkI87jo_u4MEAIQEA"; // <GPGSID>
        public const string achievement_hard_survival_master = "CgkI87jo_u4MEAIQHw"; // <GPGSID>
        public const string achievement_hard_frenzy_expert = "CgkI87jo_u4MEAIQMg"; // <GPGSID>
        public const string leaderboard_medium_anchor = "CgkI87jo_u4MEAIQUQ"; // <GPGSID>
        public const string leaderboard_hard_anchor = "CgkI87jo_u4MEAIQUg"; // <GPGSID>
        public const string leaderboard_medium_frenzy = "CgkI87jo_u4MEAIQTQ"; // <GPGSID>
        public const string leaderboard_hard_frenzy = "CgkI87jo_u4MEAIQTg"; // <GPGSID>
        public const string achievement_medium_time_attack_expert = "CgkI87jo_u4MEAIQBg"; // <GPGSID>
        public const string achievement_medium_survival_apprentice = "CgkI87jo_u4MEAIQGQ"; // <GPGSID>
        public const string leaderboard_medium_time_attack = "CgkI87jo_u4MEAIQCg"; // <GPGSID>
        public const string achievement_insane_time_attack_apprentice = "CgkI87jo_u4MEAIQEQ"; // <GPGSID>
        public const string achievement_easy_anchor_apprentice = "CgkI87jo_u4MEAIQOQ"; // <GPGSID>
        public const string achievement_insane_survival_grandmaster = "CgkI87jo_u4MEAIQJA"; // <GPGSID>
        public const string achievement_hard_time_attack_master = "CgkI87jo_u4MEAIQDw"; // <GPGSID>
        public const string achievement_insane_time_attack_expert = "CgkI87jo_u4MEAIQEg"; // <GPGSID>
        public const string leaderboard_insane_anchor = "CgkI87jo_u4MEAIQUw"; // <GPGSID>
        public const string achievement_hard_anchor_master = "CgkI87jo_u4MEAIQRg"; // <GPGSID>
        public const string leaderboard_insane_time_attack = "CgkI87jo_u4MEAIQDA"; // <GPGSID>
        public const string leaderboard_insane_frenzy = "CgkI87jo_u4MEAIQTw"; // <GPGSID>
        public const string achievement_medium_anchor_grandmaster = "CgkI87jo_u4MEAIQQA"; // <GPGSID>
        public const string achievement_hard_time_attack_apprentice = "CgkI87jo_u4MEAIQDQ"; // <GPGSID>
        public const string leaderboard_insane_survival = "CgkI87jo_u4MEAIQKg"; // <GPGSID>
        public const string achievement_medium_survival_master = "CgkI87jo_u4MEAIQGw"; // <GPGSID>
        public const string achievement_insane_frenzy_apprentice = "CgkI87jo_u4MEAIQNQ"; // <GPGSID>
        public const string achievement_easy_anchor_expert = "CgkI87jo_u4MEAIQOg"; // <GPGSID>
        public const string achievement_medium_frenzy_expert = "CgkI87jo_u4MEAIQLg"; // <GPGSID>
        public const string achievement_easy_anchor_grandmaster = "CgkI87jo_u4MEAIQPA"; // <GPGSID>
        public const string achievement_insane_frenzy_expert = "CgkI87jo_u4MEAIQNg"; // <GPGSID>
        public const string achievement_hard_survival_apprentice = "CgkI87jo_u4MEAIQHQ"; // <GPGSID>
        public const string achievement_insane_frenzy_grandmaster = "CgkI87jo_u4MEAIQOA"; // <GPGSID>
        public const string achievement_insane_survival_expert = "CgkI87jo_u4MEAIQIg"; // <GPGSID>
        public const string achievement_hard_frenzy_master = "CgkI87jo_u4MEAIQMw"; // <GPGSID>
        public const string achievement_medium_time_attack_grandmaster = "CgkI87jo_u4MEAIQCA"; // <GPGSID>
        public const string achievement_medium_frenzy_master = "CgkI87jo_u4MEAIQLw"; // <GPGSID>

}

